authors:
  anastasiia:
    name: Anastasiia But
    description: Architecture, curation, AI/ML pipeline
    url: https://www.linkedin.com/in/happyinhappy/
  anastasiya:
    name: Anastasiya Ilukhina
    description: Content, quality review
    url: https://www.linkedin.com/in/anastasiya-ilukhina-09646a289/
